### ISSUE TITLE
Doesn't work well when not serving from root

### ISSUE THREAD

**Issue by hkeio** [Quiq/docker-registry-ui#1]
Hi,
I'm using your UI for my private registry. My idea was to server the registry from `docker.domain.com` and the UI from `docker.domain.com/ui`. Unfortunately the UI can't deal with that configuration.

What I noticed:
* Event Log link is pointing to `/events`
* Table is empty (but there are entries when serving from `/`)
* Breadcrumb wrong

**Comment by roman-vynar** [comment]
Hello, thanks for using our tool. You can run UI from the root / and registry from /v2 This is actually what we do and it works perfectly. You don’t need to make any extra configuration for registry, /v2 is the only location registry is serving. All docker commands will work us normal. Let me know your thoughts.

**Comment by hkeio** [comment]
You are absolutely right! :) It's working for me as well. Thank you!
But I don't know if that's possible for all potential users of your tool.

**Comment by roman-vynar** [comment]
I was thinking about it initially but the reason I left it to be this way is URLs look like the docker image paths. 
It’s not really a problem to make it working from non-root.

**Comment by roman-vynar** [comment]
To be released in 0.7 soon today.
