### ISSUE TITLE
Deploy Docker Registry UI

### ISSUE THREAD

**Issue by galeenk** [Quiq/docker-registry-ui#19]
hai, 

i want to ask.. how to run this docker registry ui?
1. do i run docker build first? but where the example for docker build ?
2. when i run docker pull images existing and docker run, i got error like this :

> root@docker-registry:/opt/docker/docker-registry-ui# docker run -d -p 8000:8000 -v /local/config.yml:/opt/config.yml:ro     --name=registry-ui quiq/docker-registry-ui
25e5a27f5719ede17727127b2678ca68a5f9999fa559106f4e937f0e67e8ff00
root@docker-registry:/opt/docker/docker-registry-ui# docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                     PORTS               NAMES
25e5a27f5719        quiq/docker-registry-ui   "/opt/docker-registr…"   3 seconds ago       Exited (2) 2 seconds ago                       registry-ui
root@docker-registry:/opt/docker/docker-registry-ui# docker logs registry-ui
panic: read config.yml: is a directory
goroutine 1 [running]:
main.main()
        /opt/src/github.com/quiq/docker-registry-ui/main.go:71 +0x139b 

3. when i run on folder example using docker compose i got error like this :

> root@docker-registry:/opt/docker/docker-registry-ui/example# docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                      PORTS                     NAMES
1f3566d9b88c        quiq/docker-registry-ui:latest   "/opt/docker-registr…"   27 seconds ago      Exited (2) 26 seconds ago                             example_registry-ui_1
fefb2e8721e3        registry:2                       "/entrypoint.sh /etc…"   33 seconds ago      Up 32 seconds (healthy)     0.0.0.0:32768->5000/tcp   example_registry_1
80a76a5ffab1        httpd:2.4                        "httpd-foreground"       33 seconds ago      Up 32 seconds               0.0.0.0:80->80/tcp        example_httpd_1
root@docker-registry:/opt/docker/docker-registry-ui/example# docker logs example_registry-ui_1
2018-09-13 03:48:21 - registry.client - ERROR - 503 Service Unavailable
panic: cannot initialize api client or unsupported auth method
goroutine 1 [running]:
main.main()
        /opt/src/github.com/quiq/docker-registry-ui/main.go:105 +0x132a

any advice ?

**Comment by roman-vynar** [comment]
Hello,

1. You can pull an image from Docker Hub https://hub.docker.com/r/quiq/docker-registry-ui/tags/
2. You need to create your own config under /local/config.yml and then share it with the container. As long as you didn't create, Docker created a folder instead.
3. This is just an example and not supposed to work if you don't put your Docker registry credentials into config.yml.
