### ISSUE TITLE
unable to open database

### ISSUE THREAD

**Issue by danielezer** [Quiq/docker-registry-ui#2]
Hi,
I am using your registry UI and I see an error messages in stdout:
Error selecting from table: unable to open database file2018-05-03 10:42:53

what does this mean? should I be worried about that?

**Comment by stubbsd** [comment]
Not sure how you're using it. I when running it on Kubernetes I needed to mount a volume at /opt/data as the system couldn't write to that location otherwise.

**Comment by danielezer** [comment]
I am using it with a docker-compose file.
It should be able to write to that directory even without a volume. Do you think this is a permissions issue?

**Comment by roman-vynar** [comment]
You need to mount any folder to the container’s /opt/data so the ui can write sqlitedb file. Also container runs from user nobody which should be able to write to the mounted folder.

**Comment by roman-vynar** [comment]
If you don’t mount any folder to /opt/data the sqlite file will be written locally within container and this means you can’t run it with —read-only option.

**Comment by danielezer** [comment]
ok, thank you!

**Comment by rvernica** [comment]
Might be good to add this to the README.

**Comment by roman-vynar** [comment]
@rvernica I added a week ago.

**Comment by goelprateek** [comment]
Hi roman-vynar,
I am getting following error  "events.event_listener - ERROR - Error creating a table: unable to open database file" even after mounting a folder with permission 777.
