### ISSUE TITLE
Example of config.yml

### ISSUE THREAD

**Issue by tuyenpm9** [Quiq/docker-registry-ui#20]
container won't start with only this command without its `config.yml`

```
docker run -d -p 8000:8000 -v /local/config.yml:/opt/config.yml:ro \
>     --name=registry-ui quiq/docker-registry-ui
```

I wonder where to find a sample for this image or howto write one?

To extend, what would it be to use token authentication?

**Comment by roman-vynar** [comment]
https://github.com/Quiq/docker-registry-ui/blob/master/config.yml

https://github.com/cesanta/docker_auth

**Comment by tuyenpm9** [comment]
Thanks, but I have `docker_auth` installed and work perfectly with dock registry and ldap but still can't run docker-registry-ui with base config, here is my config.yml:

**Comment by roman-vynar** [comment]
Please paste the shell output of docker run on how you create container +
`docker ps -a`
`docker logs registry-ui `

There should be an error when a container is created in the first place or once started but you should see logs. What's docker version BTW?

**Comment by tuyenpm9** [comment]
Thanks with your help, I found out the issue:
I assumed /etc/hosts file wil be used by containers, turn out it's not, connections broke between containers.

After fix some url strings, it works as expected.
