### ISSUE TITLE
datatable.min.xx is loaded from cdn

### ISSUE THREAD

**Issue by agulov** [Quiq/docker-registry-ui#25]
I have no internet in my environment, so when i try to launch registry-ui in shows only table skeletons, and in browser's networking tab datatables.min.xx files are i see that they are loaded from cdn.datatables.net.

**Comment by roman-vynar** [comment]
True, need to copy those into the project
```
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/bs-3.3.5/jq-2.1.4,dt-1.10.8/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/r/bs-3.3.5/jqc-1.11.3,dt-1.10.8/datatables.min.js"></script>
```

**Comment by roman-vynar** [comment]
Done in 0.8.0.
