### ISSUE TITLE
scalability 

### ISSUE THREAD

**Issue by danielezer** [Quiq/docker-registry-ui#3]
Hi,
I see that you are using a local sqlite db. does that mean I can't start several instances of the UI behind a load balancer? Do you have any plans to integrate an external DB?

**Comment by roman-vynar** [comment]
Yes, you are right.
I think it should be fairly easy to integrate with MySQL, for example.
I will take a look once making any changes to UI.

**Comment by danielezer** [comment]
Thanks, that would be a great feature 🙂

**Comment by roman-vynar** [comment]
Added in the new release 0.6.
