### ISSUE TITLE
LogEvent says '{"message":"Method Not Allowed"}'

### ISSUE THREAD

**Issue by bartashevich** [Quiq/docker-registry-ui#30]
I'm trying to setup LogEvents, where I already setup MySQL database and now I'm trying to setup register notification.

But when I perform curl -i -H "Authorization: Bearer $TOKEN register:8000/api/events

It responds with:
HTTP/1.1 405 Method Not Allowed
Content-Type: application/json; charset=UTF-8
Date: Wed, 16 Jan 2019 12:20:32 GMT
Content-Length: 32

{"message":"Method Not Allowed"}

**Comment by roman-vynar** [comment]
/api/events takes only POST, there is no reason for GET.

**Comment by roman-vynar** [comment]
Why not to try with a real registry?

**Comment by bartashevich** [comment]
I have a register and it is using cesanta/docker_auth for the authentication. Just how can I extract token?

**Comment by roman-vynar** [comment]
Actually, there is no easy way to retrieve it, you need to enable debug and print it, then it can be used until expired.

**Comment by roman-vynar** [comment]
Closing this as there are no real issues with notification events.
