### ISSUE TITLE
Remove repository if it doesn't contain any images

### ISSUE THREAD

**Issue by straurob** [Quiq/docker-registry-ui#33]
### Steps to Reproduce
1. Push an image to your private registry.
2. Open the Docker Registry UI and visit the folder containing your pushed image.
3. Delete the image via Docker Registry UI.

### Observed Behavior
The image is removed successfully. However the parent repository remains visible with zero images.

### Feature Request
If the repository does not contain any images remove it from the list.

**Comment by roman-vynar** [comment]
https://github.com/Quiq/docker-registry-ui/commit/b6398fa33c6b311620302942e44f6c508a7d2e3b
To be released in 0.9.0 soon.
