### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by pengu-fr** [Quiq/docker-registry-ui#34]
It would be nice if the date/time displayed on the UI could use the timezone defined in an environnement variable (TZ environment variable on alpine)

**Comment by roman-vynar** [comment]
To be released in 0.9.0 soon. See https://github.com/Quiq/docker-registry-ui/commit/41e74f70a25b27994f9cfd2e1eda4ad78509b98e#diff-3254677a7917c6c01f55212f86c57fbfR18

**Comment by yurenchen000** [comment]
timezone in shell is right,
but the webpage seems still use UTC time

quiq/docker-registry-ui    0.9.5               8287046c894d        5 months ago        24MB

**Comment by coosir** [comment]
> timezone in shell is right, but the webpage seems still use UTC time
> 
> quiq/docker-registry-ui 0.9.5 8287046c894d 5 months ago 24MB

yes, webpage "Created On" still not applied. @roman-vynar

**Comment by roman-vynar** [comment]
Sorry for the 5 years delay 😀 It was the covid period, war started...

Fixed in https://github.com/Quiq/docker-registry-ui/commit/e9efdcf94a040fd5bdcdf0c6d8428a7a5c8ca158 to be released with 0.9.7.
