### ISSUE TITLE
duplicate image of library namespace

### ISSUE THREAD

**Issue by qiukeren** [Quiq/docker-registry-ui#50]
problem: 

on perticually conditions ,

`docker.registry.com/v2/_catalog` 

returns duplicate name:

```
{"repositories":["busybox","library/busybox","library/ubuntu","ubuntu"]}
```

then here adds the image twice to the list:

![image](https://user-images.githubusercontent.com/2325492/88765649-5d1bc280-d1a9-11ea-973d-8cedd376de9a.png)

then causes:

![image](https://user-images.githubusercontent.com/2325492/88765770-905e5180-d1a9-11ea-8a25-772eae8e8c19.png)

**Comment by roman-vynar** [comment]
Hello,

Any idea why your registry returns both "library/ubuntu","ubuntu"?

**Comment by qiukeren** [comment]
> Hello,
> 
> Any idea why your registry returns both "library/ubuntu","ubuntu"?

here is the reproduce code: 

```
# curl docker.homelabbity.com/v2/_catalog
get: {"repositories":["centos"]}
# docker tag centos docker.server.com/library/centos
# docker push docker.server.com/library/centos
# curl docker.homelabbity.com/v2/_catalog
get: {"repositories":["centos","library/centos"]}
```

the reigstry image is `registry:2`,`2d4f4b5309b1`,`5 weeks ago`.

**Comment by roman-vynar** [comment]
I see, you have created "library/" namespace explicitly by docker tag/push and it interferes with the built-in one.

**Comment by qiukeren** [comment]
thanks for your reply , it is my mistake.
