### ISSUE TITLE
Deleting a manifest list only deletes the first manifest

### ISSUE THREAD

**Issue by stevbev** [Quiq/docker-registry-ui#54]
I use manifest lists to cover multi-architecture images (v4.0.1 manifest list contains v4.0.1-amd64, v4.0.1-arm, v4.0.1-arm64 manifests). The UI properly displays the manifest list when clicked on and shows the expected details for the 3 amd64/arm/arm64 manifests. 

Using the Delete button for the manifest list results in the first manifest getting deleted (in my case the v4.0.1-amd64 manifest) instead of the manifest list getting removed. Additionally the automatic delete function removes the individual manifests as expected but leaves the manifest lists. The manifest lists successfully delete when passing the SHA256 hash to the docker registry REST endpoint. I think that docker-registry-ui is using the wrong digest for manifest lists.

I believe the attached log file [quiq-docker-registry-ui_delete.txt](https://github.com/Quiq/docker-registry-ui/files/5250426/quiq-docker-registry-ui_delete.txt) helps demonstrate the issue. 
- The manifest list for app_name:4.0.1 has digest "cace61c076b1f4f186f323eab626300bee5493f8d80b4e2b7ace8d303b675095"
- Manifest #1 has digest of "eaf66f4047adcb7f40ef92f66371538fdc9923ca3bfc78ddfeb937333b3adc19"

1. Line 5: docker-registry-ui GET docker-registry for the manifest list in response to the first Delete button click event for app_name:4.0.1
2. Line 8: docker-registry-ui DELETE docker-registry for the digest found in Manifest #1 used for app_name:4.0.1-amd64 instead of the digest for the manifest list
3. Line 9: docker-registry completes the DELETE command using the digest for app_name:4.0.1-amd64
4. Line 15: docker-registry-ui GET docker-registry for the manifest list in response to the first Delete button click event for app_name:4.0.1
5. Line 17: docker-registry fails on the DELETE command using the digest for app_name:4.0.1-amd64 as expected

**Comment by roman-vynar** [comment]
Thanks for the report!

Also FYI - https://github.com/Quiq/docker-registry-ui/issues/29

**Comment by stevbev** [comment]
Thank you for the reminder about #29, I did review that issue before submitting mine. #29 seems to be an issue with a manifest having multiple tags and cannot be deleted by sending the digest ID. 

The issue I encounter is different from #29 in that all manifests have a single tag per digest, but the digest of the first manifest in the manifest list is what is sent in the DELETE call instead of the digest of the manifest list.

I reviewed the code but could not determine exactly how to resolve. I believe the issue is that there are several docker API calls using the Accept header, and the specific API call I think docker-registry-ui is using for the process following the Delete button only returns the contents of the manifest list but does not include the digest for the manifest list itself. I will keep poking around and brush up on Golang to see if I can help figure it out.

**Comment by stevbev** [comment]
I think I have a lead. When clicking on a manifest list in Registry-UI, docker registry logs state msg="rewriting manifest list sha256:d0df...1fdf in schema1 format to support old client". This indicates Registry-UI is not adding HTTP header "Accept: application/vnd.docker.distribution.manifest.list.v2+json". 

When this header is added to the API call the manifest list digest is returned in HTTP header "Docker-Content-Digest", and the digest of manifests is found in the body. Perhaps adding the Accept header will provide a standard method to obtain the digest for manifest lists and manifests for the Delete function.

**Comment by stevbev** [comment]
I think I have found a solution. For v2 registry, passing two Accept headers in the request message returns the expected digest in Docker-Content-Digest response header if the tag is a manifest-list or manifest.

Example:
Accept: application/vnd.docker.distribution.manifest.v2+json
Accept: application/vnd.docker.distribution.manifest.list.v2+json

I had a look at the registry-ui code and see the Accept header is using inline .Set() on the HTTP call in _**registry/client.go**_. I am not familiar enough with golang to convert from inline .Set() to setting the HTTP headers from an array. I think if the callRegistry() function could be updated to change _**manifestFormat**_ from string to []string (or similar type), then it should be possible to send multiple Accept headers to get the desired behavior to delete manifest lists.

**Comment by stevbev** [comment]
I studied the code a bit further and performed testing, the multiple Accept header does not seem a feasible solution. The _**gorequest**_ module does not seem to support duplicate headers.

Instead there seems to be a trivial solution that exists in _**DeleteTag()**_. _**DeleteTag()**_ calls _**callRegistry()**_ using _manifest.v2_ only. I have added 4 lines that first try _manifest.list.v2_ and if the _Content-Type_ is not for manifest.list.v2 then a second call is made using _manifest.v2_. This approach allows the manifests and manifest lists to be deleted manually as well as the automatically by the Purge task. I will prepare a pull request for this.

**Comment by roman-vynar** [comment]
Thanks!

https://github.com/Quiq/docker-registry-ui/pull/55
