### ISSUE TITLE
Restrict access to events

### ISSUE THREAD

**Issue by ribbybibby** [Quiq/docker-registry-ui#58]
The event log (at /events and on the individual tag pages) contains some potentially identifying information such as the association between user/IP that you may not want to share widely with everyone.

Would it be possible to optionally restrict events visibility to admins, in the same way that you can restrict delete permissions?

Something like this in the config file:
```
# If users can view events. If set to False, then only admins listed below.
anyone_can_view_events: false
```

**Comment by roman-vynar** [comment]
Will be released with 0.9.5
