### ISSUE TITLE
Can't build, dependency issue

### ISSUE THREAD

**Issue by dmaes** [Quiq/docker-registry-ui#64]
When trying to `go build` there seems to be a dependency issue:
```
go: github.com/mattn/go-sqlite3@v2.0.3+incompatible: reading github.com/mattn/go-sqlite3/go.mod at revision v2.0.3: unknown revision v2.0.3
```
Looking at https://github.com/mattn/go-sqlite3, there seems to be no v2 (there was at one point, but was a mistake ?)

**Comment by roman-vynar** [comment]
Looks like they messed something. 
See this https://pkg.go.dev/github.com/mattn/go-sqlite3@v2.0.3+incompatible
```
Warning  Retracted: Accidental; no major changes or features.
```

Then click `Go to latest` and see this https://pkg.go.dev/github.com/mattn/go-sqlite3 
```
Latest stable version is v1.14 or later, not v2.

NOTE: The increase to v2 was an accident. There were no major changes or features.
```

**Comment by roman-vynar** [comment]
I have pushed the fix https://github.com/Quiq/docker-registry-ui/commit/901beb5c9bd435de0d4485bec372cf4e0466db87

**Comment by dmaes** [comment]
It does indeed, thanks!
