### ISSUE TITLE
Home screen does not show New Namespace or reflect new repos without the restart of container

### ISSUE THREAD

**Issue by spanhotra** [Quiq/docker-registry-ui#67]
Expected: As and when I push a new image, it should be visible on the UI with the new namespace

eg

podman push localhost:5000/dev/image:v1

it should create a new namespace dev  and add image with tag v1

Unless I restart the container with podman-compose restart. It does not show up.

**Comment by roman-vynar** [comment]
Repo list refresh is not an online operation because it takes time and slow.
There is a cache, did you wait for 10 min.?


```
* Caching the list of repositories, tag counts and refreshing in background
```
```
# Cache refresh interval in minutes.
# How long to cache repository list and tag counts.
cache_refresh_interval: 10
```
Tags appear immediately because it's different but the new repos do not.

**Comment by spanhotra** [comment]
Thank you @roman-vynar for the information
