### ISSUE TITLE
panic: event_database_driver should be either sqlite3 or mysql

### ISSUE THREAD

**Issue by skyfx64** [Quiq/docker-registry-ui#7]
Hello,

after update latest version the app cannot running.

Error message.
panic: event_database_driver should be either sqlite3 or mysql

Please help Thanks'
<img width="912" alt="screen shot 2018-05-30 at 11 57 25" src="https://user-images.githubusercontent.com/20234920/40699790-aefd27a6-6400-11e8-8e16-832c9358cfff.png">

**Comment by roman-vynar** [comment]
Please check out the upgrade note https://github.com/Quiq/docker-registry-ui/releases/tag/0.6

You need to add 2 lines to your config https://github.com/Quiq/docker-registry-ui/blob/master/config.yml#L22
