### ISSUE TITLE
The home page can only list 100 images.

### ISSUE THREAD

**Issue by zhoulouzi** [Quiq/docker-registry-ui#9]
According to the [docker registry api reference](https://docs.docker.com/registry/spec/api/#listing-repositories)

>  A registry may also limit the amount of responses returned even if pagination was not explicitly requested

so in registry/client.go . it  was 
`data, _ := c.callRegistry("/v2/_catalog", scope, 2, false)`
the api only return 100 results.

I am not good at golang coding，could any one help to change this？

Thanks

**Comment by ghostsquad** [comment]
any update on this?

**Comment by leenheer** [comment]
Also interested to know if there are any updates? Thanks!

**Comment by roman-vynar** [comment]
Docker Registry 2.7.0 has been released yesterday, so I will be looking into this and what have changed  soon.

**Comment by roman-vynar** [comment]
Done in 0.8.0.
